language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
jobs:
  allow_failures:
    - python: "nightly"
install: pip install .
script: python -m unittest discover
